//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFrameworkWithADONet.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPTable
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpLastname { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string ContactNo { get; set; }
    }
}
